# Generated by Django 5.0.1 on 2024-04-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='father',
            field=models.CharField(default='monir', max_length=15),
        ),
    ]
