# Generated by Django 5.0.4 on 2024-04-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=20)),
            ],
        ),
    ]
