# Generated by Django 5.0.4 on 2024-04-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module14App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='father_name',
            field=models.CharField(default='Murad', max_length=20),
        ),
    ]
