# Generated by Django 5.0.4 on 2024-04-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module14App', '0002_students_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='wrok',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=20)),
            ],
        ),
    ]
