# Generated by Django 5.0.4 on 2024-04-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module14App', '0003_wrok'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wrok',
            new_name='work',
        ),
    ]
