# Generated by Django 5.0.1 on 2024-04-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='mothername',
            field=models.CharField(default='None', max_length=25),
        ),
    ]
